### ISSUE TITLE
QUESTION: What are the steps to use this on nix-os? Also, any plans of pushing dfx to the nix package repository?

### ISSUE THREAD

**Issue by saikatdas0790** [ninegua/ic-nix#36]

**Comment by ninegua** [comment]
> What are the steps to use this on NixOS?

As stated in the README, simply run this command should be enough to drop into a shell with a working `dfx` in PATH: 

```
nix-shell https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz
```

> Any plans of pushing dfx to the nix package repository?

Please note that this repository is not meant to be an "official" or "unofficial" release of dfx. It is more like a "nightly" build of latest IC binaries, from which `dfx` may (or may not) work out of box.

The difference is that the "official" release of dfx bundles specific versions of replica and other binaries, while this repository just builds the latest of everything, which may or may not work well together.

**Comment by saikatdas0790** [comment]
The official install method with the install script doesn't work out of the box on NixOS.

I believe this repo already has all the work laid out for an official Nix package for dfx to be created/uploaded to the Nix package repository.

ic-nix has a lot of additional Motoko things available that might not be relevant for a Rust canister developer.

Thoughts?

**Comment by ninegua** [comment]
I am on NixOS myself. So did you run into errors when running the above `nix-shell` command?

**Comment by saikatdas0790** [comment]
Ok. I will try. I remember reading in quite a few places that `nix-env` usage is discouraged since it doesn't let you declaratively define the packages in your installation

**Comment by saikatdas0790** [comment]
@ninegua 
I think I'm getting it now. What would a starter `shell.nix` look like?

**Comment by ninegua** [comment]
You can have a `shell.nix` consisting of a single line like this:

```
import (fetchTarball https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz) { version = "20230101"; }
```

**Comment by saikatdas0790** [comment]
@ninegua 

I have a `shell.nix` file that looks like this

```nix
let
  dfx-env = import (fetchTarball https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz) { version = "20230101"; };
in
dfx-env.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [ nodejs-16_x ];
})
```

but running `nix-shell` gives me this:
![image](https://user-images.githubusercontent.com/7412443/215049924-f6c55e6f-76b9-41d1-98f3-0f2d49ed87b7.png)

Something I'm missing?

**Comment by ninegua** [comment]
Your NixOS version may not have this `nodejs-16_x` package. You can just use `nodejs` instead.

**Comment by saikatdas0790** [comment]
@ninegua I'm fairly certain that isn't the issue

Here's `nodejs`
![image](https://user-images.githubusercontent.com/7412443/215118258-10b2b323-9be9-4247-b13a-a16fe8f0582d.png)

Here's `rustup`
![image](https://user-images.githubusercontent.com/7412443/215118341-2f8e0926-a1c6-4551-892e-f1cb34cb4e01.png)

And I'm on the latest stable NixOS, which is **22.11** and searching its packages list tells me that it does have it.

Having said that, what's the easiest way to get Rust and its corresponding toolchains also added to the `ic-nix` generated shell?

**Comment by ninegua** [comment]
Oh, I see. What was missing is this:

```
{ pkgs ? import <nixpkgs> {} }:
with pkgs;
let ...
```

**Comment by ninegua** [comment]
For rust, I just use `rustup`, which can be added to the dependency list.
