### ISSUE TITLE
Request: Add test-state-machine-client to ic-nix as part of the packaged binaries

### ISSUE THREAD

**Issue by saikatdas0790** [ninegua/ic-nix#38]
Hi @ninegua 
I am referring to [this new binary](https://github.com/dfinity/test-state-machine-client). Thoughts?

**Comment by ninegua** [comment]
I don't think it is a widely used utility, so I'm hesitant to include it as part of the distribution, because we can't include everything in ic-nix build. It also looks like a straight-forward rust repo that can be built using rustup or cargo. So if you want the binary, you can go ahead a build it yourself.

**Comment by saikatdas0790** [comment]
I'm using this `shell.nix` to add the additional packages I need to my dev environment and then using direnv to setup a dev environment.

```nix
{ pkgs ? import <nixpkgs> { } }:
let
  dfx-env = import (fetchTarball https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz) { version = "20230101"; };
in
dfx-env.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.rustup pkgs.pkg-config pkgs.openssl pkgs.protobuf pkgs.cmake pkgs.cachix pkgs.killall ];
})
```

How would I add the prebuilt binary for `test-state-machine-client` package to this and make the binary available in the environment?

I believe this package should be added to ic-nix since it's the official successor to `ic-state-machine-tests` which is the accepted way to perform integration testing for Rust projects and it's part of the core set of tools one would expect to be present for IC development using Rust

**Comment by ninegua** [comment]
If you are looking for ways of including rust packages in your nix setup, you can start from this guide https://ryantm.github.io/nixpkgs/languages-frameworks/rust/. Your above `shell.nix` is already a good demonstration that not every dependencies for your own setup have to come from `ic-nix` itself.

**Comment by saikatdas0790** [comment]
Hi @ninegua 

The thing is, this is this is not a rust package. It is a IC specific binary like `ic-repl` or `candid`. It would make a lot of sense for this binary to be available as part of `ic-nix`.

For example, the constructor for the state machine [here](https://docs.rs/ic-test-state-machine-client/1.1.1/ic_test_state_machine_client/struct.StateMachine.html#method.new) requires the binary to be present for the library to be initialized. 

The `internet-identity` repo uses it like this:
https://github.com/dfinity/internet-identity/blob/e9cbaae4f52e65abd9e7f00aa622da74b88437c3/src/canister_tests/src/framework.rs#L125-L151

It requires the binary to be present in the path.

With `ic-nix`, this could really improve usability if this binary were made available as part of the Nix shell environment.

Thoughts?

**Comment by ninegua** [comment]
I think I finally understood what you are asking for. This https://github.com/dfinity/test-state-machine-client is just a library, and the actual binary is built as part of https://github.com/dfinity/ic repository. 

Also, according to this [Cargo.toml](https://github.com/dfinity/ic/blob/master/rs/state_machine_tests/Cargo.toml), the binary is call `ic-state-machine-tests` instead. Probably the `internet-identity` repo is using it under a different name?

**Comment by saikatdas0790** [comment]
@ninegua So, `ic-state-machine-tests` is an older dependency that was needed to be built from the `dfinity/ic` repo directly by referencing a commit hash. This new library/binary combo provides the binary in a prebuilt format. And it has all its dependencies updated to use more modern counterparts. Here is a thread from the forums that summarizes this:
https://forum.dfinity.org/t/ic-state-machine-tests-has-a-lot-of-outdated-dependencies/17909

Please add the binary to ic-nix as this would alleviate a lot of the headache and then we can just reference the binary using an environment variable as illustrated in this code here:
https://github.com/dfinity/internet-identity/blob/main/src/canister_tests/src/framework.rs#L125-L151

**Comment by saikatdas0790** [comment]
@ninegua Thank you so much. I will try this and come back in case any issues

**Comment by saikatdas0790** [comment]
@ninegua After updating to the above, this is what I am getting:
![image](https://user-images.githubusercontent.com/7412443/224968876-e8c88aef-59a8-43e9-9ba7-7bc60275bc94.png)

This is my shell.nix
```nix
{ pkgs ? import <nixpkgs> { } }:
let
  ic-nix = pkgs.fetchFromGitHub {
    owner = "ninegua";
    repo = "ic-nix";
    rev = "0c8c6808a88d650b5546a60a073853f6ceae97cc";
    sha256 = "sha256-MiK4vw4TLjXN3VH24+yeUvV7Qy2zbtKr5io/lafXjVA=";
  };
  dfx-env = pkgs.callPackage "${ic-nix}/dfx-env.nix" {
    force = true;
    inherit pkgs ic-nix;
  };
in
dfx-env.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.rustup pkgs.pkg-config pkgs.openssl pkgs.protobuf pkgs.cmake pkgs.cachix pkgs.killall ];
})

```

**Comment by saikatdas0790** [comment]
@ninegua I am also running into this error and unable to start dfx when I revert to my older shell.nix

Please advise on how to proceed
![image](https://user-images.githubusercontent.com/7412443/224969779-ad926039-ffc2-4a46-a58c-46dcdc12a83d.png)

**Comment by saikatdas0790** [comment]
Hi @ninegua 

I also tried specifying the newer version in my old `shell.nix` file like this:
```nix
{ pkgs ? import <nixpkgs> { } }:
let
  dfx-env = import (fetchTarball https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz) { version = "20230314"; };
in
dfx-env.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.rustup pkgs.pkg-config pkgs.openssl pkgs.protobuf pkgs.cmake pkgs.cachix pkgs.killall ];
})
```

This upgraded me to DFX v0.13.1 but now builds are breaking with this message.
![image](https://user-images.githubusercontent.com/7412443/224994268-4b5965d9-30f1-46ee-8739-e9d8868ed609.png)

And this has broken my local dev environment. How do I go back to using the earlier ic-nix version. I tried simply updating the version to the older version but my build environment is still using the newer dfx version.

Please help

**Comment by ninegua** [comment]
> @ninegua After updating to the above, this is what I am getting: ![image](https://user-images.githubusercontent.com/7412443/224969096-a385daa7-0bb7-429e-98ed-630372ad2db9.png)
> 
> This is my shell.nix
> 
> ```nix
> { pkgs ? import <nixpkgs> { } }:
> let
>   ic-nix = pkgs.fetchFromGitHub {
>     owner = "ninegua";
>     repo = "ic-nix";
>     rev = "0c8c6808a88d650b5546a60a073853f6ceae97cc";
>     sha256 = "sha256-MiK4vw4TLjXN3VH24+yeUvV7Qy2zbtKr5io/lafXjVA=";
>   };
>   dfx-env = pkgs.callPackage "${ic-nix}/dfx-env.nix" {
>     force = true;
>     inherit pkgs ic-nix;
>   };
> in
> dfx-env.overrideAttrs (old: {
>   nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.rustup pkgs.pkg-config pkgs.openssl pkgs.protobuf pkgs.cmake pkgs.cachix pkgs.killall ];
> })
> ```

Which NixOS version are you using?

**Comment by ninegua** [comment]
> Hi @ninegua
> 
> I also tried specifying the newer version in my old `shell.nix` file like this:
> 
> ```nix
> { pkgs ? import <nixpkgs> { } }:
> let
>   dfx-env = import (fetchTarball https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz) { version = "20230314"; };
> in
> dfx-env.overrideAttrs (old: {
>   nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.rustup pkgs.pkg-config pkgs.openssl pkgs.protobuf pkgs.cmake pkgs.cachix pkgs.killall ];
> })
> ```
> 
> This upgraded me to DFX v0.13.1 but now builds are breaking with this message. ![image](https://user-images.githubusercontent.com/7412443/224994268-4b5965d9-30f1-46ee-8739-e9d8868ed609.png)
> 
> And this has broken my local dev environment. How do I go back to using the earlier ic-nix version. I tried simply updating the version to the older version but my build environment is still using the newer dfx version.
> 
> Please help

This particular error message doesn't look like related to ic-nix. Please check your own program to make sure you didn't have anything like `principal ""`, which is not allowed.

**Comment by saikatdas0790** [comment]
> Which NixOS version are you using?

I am on NixOS unstable

**Comment by ninegua** [comment]
The following error seems to be an open issue on "unstable" https://github.com/Nix-QChem/NixOS-QChem/issues/262#issuecomment-1458263684

```
error: The ‘env’ attribute set cannot contain any attributes passed to derivation. The following attributes are overlapping: NIX_CFLAGS_COMPILE
```

To fix this, you will need to pin nixpkgs to nixos-22.11 channel. Here is one way of doing this:

```
nix-channel --add https:///nixos.org/channels/nixos-22.11
nix-channel --update nixos-22.11
```

This will download a copy of the latest nixos-22.11 to your computer. Then with the new version of the shell.nix as [you gave here](https://github.com/ninegua/ic-nix/issues/38#issuecomment-1468113834), modify the first line to be:

```
{ pkgs ? import <nixos-22.11/nixpkgs> { } }:
```

Then you may try running `nix-shell` and see if this pinning works for you.

**Comment by saikatdas0790** [comment]
Hi @ninegua 

The nixpkgs is not found as shown in the error. What is the right way to set the $NIX_PATH?

![image](https://user-images.githubusercontent.com/7412443/225217722-350c3383-f246-4c4c-9a5c-1f580bb11d44.png)

**Comment by saikatdas0790** [comment]
Hi @ninegua 

I have tried pinning the nixpkgs to nixos-22.11 as you suggested but I'm still seeing this error:
![image](https://user-images.githubusercontent.com/7412443/225218921-a66342fe-1154-424d-b26d-f23e7ee5ff0b.png)

My shell.nix looks like this now:
```nix
{ pkgs ? import <nixos-22.11/nixpkgs> { } }:
let
  dfx-env = import (fetchTarball https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz) { version = "20230101"; };
in
dfx-env.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.rustup pkgs.pkg-config pkgs.openssl pkgs.protobuf pkgs.cmake pkgs.cachix pkgs.killall ];
})
```

**Comment by ninegua** [comment]
Please change the `dfx-env = ...` line to the following

```
  ic-nix = pkgs.fetchFromGitHub {
    owner = "ninegua";
    repo = "ic-nix";
    rev = "0c8c6808a88d650b5546a60a073853f6ceae97cc";
    sha256 = "sha256-MiK4vw4TLjXN3VH24+yeUvV7Qy2zbtKr5io/lafXjVA=";
  };
  dfx-env = pkgs.callPackage "${ic-nix}/dfx-env.nix" {
    force = true;
    inherit pkgs ic-nix;
  };
```

**Comment by saikatdas0790** [comment]
@ninegua The above is working for me now. Just an added suggestion.

The binary path is currently made available using the env variable `DFX_IC_STATE_MACHINE_TESTS_PATH`

However, the II repo uses this env variable for referencing to it: `STATE_MACHINE_BINARY`
as seen [here](https://github.com/dfinity/internet-identity/blob/26dd9ddb96a35e04ab87fddd170d0813b0f88f3f/src/canister_tests/src/framework.rs#L125-L151)

Do you think this package should use the same? Or should the II repo update theirs. I believe the name you set is more verbose and self-explanatory and would lead to a lesser chance of collision with another variable set.

Anyway, please feel free to close this issue.

Thank you for patiently walking through the issue with me and helping reach a resolution. :)

**Comment by saikatdas0790** [comment]
Hi @ninegua 

Please update ic-test-state-machine-client to the latest version v2.1.0 as mentioned here:
https://github.com/dfinity/test-state-machine-client/issues/13#issuecomment-1506833532

Thank you
