### ISSUE TITLE
UPDATE: Upgrade the test client binary to the latest

### ISSUE THREAD

**Issue by saikatdas0790** [ninegua/ic-nix#45]
Hi @ninegua 

There were some breaking changes in the test client binary and they have now been fixed and updated. Could you please update ic-nix to pull in that binary? Thank you.

Here's the relevant discussion from that repo:
https://github.com/dfinity/test-state-machine-client/issues/9#issuecomment-1479052838

**Comment by saikatdas0790** [comment]
Hi @ninegua 

I noticed that you merged [this commit](https://github.com/ninegua/ic-nix/commit/2f3b6dd341860f94e9bffaeb97e250340ee1b27b)

Quick question, for the `pkgs.fetchFromGithub` input parameters, where do we obtain the `sha256` parameter value for the merge commit?

**Comment by ninegua** [comment]
There are some useful tips here https://github.com/NixOS/nixpkgs/issues/191128

Personally I often just put in a dummy hash (32 zeros), and wait until build fails, where it would give the expected hash value as part of the error message.

**Comment by ninegua** [comment]
Also the test binary should be updated in the latest main branch. Once it finished building, I will make a new release. Then you can try it out

**Comment by saikatdas0790** [comment]
Hi @ninegua 

I am trying to deploy to Github actions using [this action](https://github.com/rikhuijzer/cache-install) but seeing this error:
![image](https://user-images.githubusercontent.com/7412443/229367744-8cac49a1-6a2c-4605-9965-a06f9cd561f0.png)

This is what my default.nix looks like now:
```nix
{ pkgs ? import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/22.11.tar.gz") { } }:
let
  dfx-env = import (builtins.fetchTarball "https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz") { version = "20230330"; };
in
dfx-env.overrideAttrs (old: {
  nativeBuildInputs = with pkgs; old.nativeBuildInputs ++
    [ rustup pkg-config openssl protobuf cmake cachix killall ];

  shellHook = ''
    rustup toolchain install stable
    rustup target add wasm32-unknown-unknown
  '';
})
```

Any thoughts on how to fix this?

**Comment by ninegua** [comment]
I have not used cache-install, so I wouldn't know why nixpkgs isn't defined in the environment. Maybe you can try modify this line `let dfx-env = import (...) { version = "20230330"; };` to `let dfx-env = import (...) { version = "20230330"; inherit pkgs; };`
