### ISSUE TITLE
Request: Please add `sns-quill` to `ic-nix`

### ISSUE THREAD

**Issue by saikatdas0790** [ninegua/ic-nix#48]
Hi @ninegua 

[This](https://github.com/dfinity/sns-quill)

As we start exploring the SNS, this would be a prerequisite for us to move forward.

It makes sense to bundle [quill](https://github.com/dfinity/quill) as well as it is used for the SNS deployment as well

Thoughts?

**Comment by ninegua** [comment]
At the moment it is rather difficult to build quill (or sns-quill) from nix (or anything that depends on the `ic` crate), because of [this issue with "cargo vendor"](https://github.com/NixOS/nixpkgs/issues/30742). So I would suggest you directly use the binary release of quill (or sns-quill) instead.

**Comment by saikatdas0790** [comment]
@ninegua 

I am trying to access the `sns-cli` mentioned [here](https://internetcomputer.org/docs/current/developer-docs/integrations/sns/get-sns/preparation#initial-parameters)

But dfx cache doesn't have it on ic-nix and the other link provided is an internal link. Thoughts on how to access it?

**Comment by ninegua** [comment]
`sns-cli` is added by #49

**Comment by saikatdas0790** [comment]
Hi @ninegua 

`dfx nns` subcommands also fail due to the read only nature of the NNS installation. Thoughts?

![image](https://user-images.githubusercontent.com/7412443/234874132-2281e336-02ba-4045-bcbb-8c008cc0959c.png)

**Comment by saikatdas0790** [comment]
> `sns-cli` is added by #49

Thank you so much for this, by the way :)

**Comment by ninegua** [comment]
`dfx nns install` is fixed in the latest release.

**Comment by saikatdas0790** [comment]
> `dfx nns install` is fixed in the latest release.

Thank you. I will test this and come back if I have any further questions :)

**Comment by saikatdas0790** [comment]
> `dfx nns install` is fixed in the latest release.

Hi @ninegua 

The `dfx nns install` seems to work fine but the local Internet Identity installed doesn't seem to work.
After the command is done executing, opening the nns-dapp URL provided in the output opens the NNS dapp but clicking on "Sign in" just opens a blank page.


Please have a look and let me know if there's any additional info I can provide.

**Comment by ninegua** [comment]
Fixing it with #55 

Will merge and make a new release once it passed CI.

**Comment by saikatdas0790** [comment]
> Fixing it with #55
> 
> Will merge and make a new release once it passed CI.

Hi @ninegua ,

I was able to get further and login with Internet Identity but now the NNS doesn't seem to be working

![image](https://user-images.githubusercontent.com/7412443/236778965-7cb6a83c-703b-498f-9428-516d9b8b391f.png)

This is what we're seeing now

It would be really helpful if you could try out [this workflow](https://internetcomputer.org/docs/current/developer-docs/integrations/sns/get-sns/local-testing) once when you're testing on your end. Would not need for us to do this back and forth :)

Thank you for all the help ❤️

**Comment by ninegua** [comment]
NNS seems to be working for me. Which browser are you using? Firefox doesn't work for me, and I had to use Chrome.

Also, the SNS workflow documentation is outdated, and I believe people are working on updating it, but I don't know estimated date for that to be available.

**Comment by ninegua** [comment]
I was able to get 100000000 ICP. Maybe your input is too high a number :-)

**Comment by saikatdas0790** [comment]
> I was able to get 100000000 ICP. Maybe your input is too high a number :-)

Yes, that worked for me as well. Thank you 🙂
