### ISSUE TITLE
Is it possible to pas an argument to nix-shell --pure to use additional packages in the shell?

### ISSUE THREAD

**Issue by Pitometsu** [ninegua/ic-nix#59]
It would be useful to let user to use other packages, e.g. `gitMinimal` or `gnumake` at the `nix-shell`, while shell is pure.  Could it be passed by arguments?  And would it be still possible to re-use binary cache for huge packages like `dfx` and canisters?

**Comment by Pitometsu** [comment]
Would it make sense to use `flakes`?

**Comment by ninegua** [comment]
The usual approach is to write your own `shell.nix` file, and add extra packages in there. I gave [an example in this discussion](https://github.com/ninegua/ic-nix/issues/38#issuecomment-1466270202), let me know if you have any success.

**Comment by ninegua** [comment]
A simpler alternative of writing `shell.nix` is something like below:

```
{ pkgs ? import <nixpkgs> { } }:
with pkgs; let
  dfx-env = import (fetchTarball https://github.com/ninegua/ic-nix/releases/download/20230508/dfx-env.tar.gz) {};
in dfx-env.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [
   # list the extra packages here
  ];
})
```

It uses release binary (so please first check if the particular release supports your machine architecture) instead of compiling from source (of a given revision & sha256 hash).

**Comment by Pitometsu** [comment]
Can I re-use binary cache of `dfx-env` in my custom `shell.nix` then?  Because it really takes long and noticeable amount of memory to build.

**Comment by Pitometsu** [comment]
Looks like next works for me, thank you:
```sh
$ nix-shell -E "
```
```nix
with import <nixpkgs> {}; let
  dfx-env = import (fetchTarball https://github.com/ninegua/ic-nix/releases/latest/download/dfx-env.tar.gz) {};
in dfx-env.overrideAttrs (old: {
  nativeBuildInputs = old.nativeBuildInputs ++ [
    (import ./mops.nix {})
    wasmtime
    coreutils cacert gnupg less which tree ripgrep gitMinimal gnumake
  ];
})
```
```sh
"
```

**Comment by Pitometsu** [comment]
Or simpler:
```sh
nix-shell https://codeload.github.com/gist/c247945f8ef2db0aefc7b393596b4de3/zip/2b7a7c36d0321373afa93b7ce21b4687e4754791
```
https://gist.github.com/Pitometsu/c247945f8ef2db0aefc7b393596b4de3

**Comment by Pitometsu** [comment]
FYI @nomeata and thanks for provided snippets.

**Comment by Pitometsu** [comment]
And for `direnv` integration with the code editor of your choice:
```sh
echo 'use nix --pure --keep DIRENV_DUMP_FILE_PATH https://codeload.github.com/gist/c247945f8ef2db0aefc7b393596b4de3/zip/2b7a7c36d0321373afa93b7ce21b4687e4754791
' > ./.envrc
nix profile install nixpkgs#direnv
nix profile install nixpkgs#nix-direnv
echo 'source $HOME/.nix-profile/share/nix-direnv/direnvrc' > ~/.config/direnv/direnvrc
cat >> ~/.config/nix/nix.conf <<EOF
keep-derivations = true
keep-outputs = true
EOF
direnv allow
```
